language: go

go:
  - 1.13.x

env:
  global:
    - VERSION=$TRAVIS_TAG

git:
  depth: false

before_install:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 
    go build -a -tags netgo -ldflags '-w -extldflags "-static"' 
    -o target/acmenator_${VERSION}_linux_amd64 .
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 
    go build -a -tags netgo -ldflags '-w -extldflags "-static"' 
    -o target/acmenator_${VERSION}_darwin_amd64 .

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: target/*
  skip_cleanup: true
  on:
    tags: true
