sudo: required

language: go

go:
  - 1.13.x

git:
  depth: false

services: 
  - docker

before_install:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  - docker build --no-cache -t $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT .

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag $IMAGE_NAME $IMAGE_NAME:latest

deploy:
  provider: script
  script: docker push $IMAGE_NAME:latest
  on:
    branch: master

